# This file was generated by GoReleaser. DO NOT EDIT.
cask "devopsify" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "315745468fc6134e2d2fd30da3d82081a51f294ac8f5bbda51da1d465d9a0f3b"
      url "https://github.com/java-rakhmonaliev/devops-cli/releases/download/v#{version}/devopsify_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d3069254f25a360226bdb08dda5dbc56bff41432889d1af7f817967ac978ccc4"
      url "https://github.com/java-rakhmonaliev/devops-cli/releases/download/v#{version}/devopsify_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "467f6a0dca8f72b2ae03f7c15fc13243fe22391e0543bc98f2fa837724f104c3"
      url "https://github.com/java-rakhmonaliev/devops-cli/releases/download/v#{version}/devopsify_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "73997d51cac3c14d3bc40c1764ad9d4aba1a64e74b4b87f55dc8a8d23deff3f2"
      url "https://github.com/java-rakhmonaliev/devops-cli/releases/download/v#{version}/devopsify_linux_arm64.tar.gz"
    end
  end

  name "devopsify"
  desc "One command to containerize, provision and ship any app to a VPS"
  homepage "https://github.com/java-rakhmonaliev/devops-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "devopsify"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/devopsify"]
    end
  end

  # No zap stanza required

end
